"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import { AuthProvider } from "./context/auth";
import { useState } from "react";
// Font Awesomeの設定
import "@fortawesome/fontawesome-svg-core/styles.css";
import NextAuthProvider from "@/providers/NextAuth";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isAuth, setIsAuth] = useState<boolean>(false);

  return (
    <html lang="en" className="bg-cyan-50">
      <body className={inter.className} suppressHydrationWarning={true}>
        <NextAuthProvider>
          <AuthProvider
            authInfo={{
              isAuth,
              setIsAuth,
            }}
          >
            <Navbar />
            {children}
          </AuthProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
