"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./Navbar";
import { AuthProvider } from "./context/auth";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isAuth, setIsAuth] = useState<boolean>(false);

  return (
    <html lang="en" className="bg-teal-50">
      <body className={inter.className} suppressHydrationWarning={true}>
        <AuthProvider
          authInfo={{
            isAuth,
            setIsAuth,
          }}
        >
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
